/* eslint-disable @typescript-eslint/no-require-imports */
const React = require('react');

const MockIcon = React.forwardRef((props, ref) => 
  React.createElement('svg', { ...props, ref, 'data-testid': 'mock-icon' })
);

MockIcon.displayName = 'MockIcon';

module.exports = {
  DownloadIcon: MockIcon,
  BellIcon: MockIcon,
  MoreDotIcon: MockIcon,
  FileIcon: MockIcon,
  GridIcon: MockIcon,
  AudioIcon: MockIcon,
  VideoIcon: MockIcon,
  BoltIcon: MockIcon,
  PlusIcon: MockIcon,
  BoxIcon: MockIcon,
  CloseIcon: MockIcon,
  CheckCircleIcon: MockIcon,
  AlertIcon: MockIcon,
  InfoIcon: MockIcon,
  ErrorIcon: MockIcon,
  ArrowUpIcon: MockIcon,
  FolderIcon: MockIcon,
  ArrowDownIcon: MockIcon,
  ArrowRightIcon: MockIcon,
  GroupIcon: MockIcon,
  BoxIconLine: MockIcon,
  ShootingStarIcon: MockIcon,
  DollarLineIcon: MockIcon,
  TrashBinIcon: MockIcon,
  AngleUpIcon: MockIcon,
  AngleDownIcon: MockIcon,
  PencilIcon: MockIcon,
  CheckLineIcon: MockIcon,
  CloseLineIcon: MockIcon,
  ChevronDownIcon: MockIcon,
  PaperPlaneIcon: MockIcon,
  EnvelopeIcon: MockIcon,
  LockIcon: MockIcon,
  UserIcon: MockIcon,
  CalenderIcon: MockIcon,
  EyeIcon: MockIcon,
  EyeCloseIcon: MockIcon,
  TimeIcon: MockIcon,
  CopyIcon: MockIcon,
  ChevronLeftIcon: MockIcon,
  UserCircleIcon: MockIcon,
  ListIcon: MockIcon,
  TableIcon: MockIcon,
  PageIcon: MockIcon,
  TaskIcon: MockIcon,
  PieChartIcon: MockIcon,
  BoxCubeIcon: MockIcon,
  PlugInIcon: MockIcon,
  DocsIcon: MockIcon,
  MailIcon: MockIcon,
  HorizontaLDots: MockIcon,
  ChevronUpIcon: MockIcon,
  ChatIcon: MockIcon,
  CatalogIcon: MockIcon,
};
